services:
  dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /app/REPOSITORY_NAME
      - type: bind
        source: ~/.gitconfig
        target: /home/vscode/.gitconfig
      # for GitHub repository (with GitHub CLI)
      - type: bind
        source: ~/.config/gh
        target: /home/vscode/.config/gh
      # for AWS develepment
      # - type: bind
      #   source: ~/.aws
      #   target: /home/vscode/.aws

## If you want to use CUDA in the container, uncomment the following lines.
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [ gpu ]
#              count: all
