version: '3'
services:
  dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/workspace/TEMP
      - /workspace/TEMP/dist/
      - $HOME/.ssh:/home/docker-user/.ssh
      - $HOME/.akr:/home/docker-user/.akr  # if needed
